sudo: required
dist: bionic
language: cshapr
mono: none
dotnet: 5.0
services: docker
before_install:
  - cd RestWithASP-NET5/
  - echo "We are in the right folder!"
script:
  - docker-compose build
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script:
    docker tag rest-with-asp-net5:latest $DOCKER_USERNAME/rest-with-asp-net5:$TRAVIS_JOB_ID;
    docker tag rest-with-asp-net5-db:latest $DOCKER_USERNAME/rest-with-asp-net5-db:$TRAVIS_JOB_ID;
    docker tag $DOCKER_USERNAME/rest-with-asp-net5:$TRAVIS_JOB_ID;
    docker tag $DOCKER_USERNAME/rest-with-asp-net5-db?$TRAVIS_JOB_ID;
  on:
    branch: main
notifications:
  email: false
